menus/urls.py
from django.conf.urls import url
from .views import ItemListView, ItemDetailView, ItemCreateView, ItemUpdateView

urlpatterns = [
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    # url(r'^(?P<pk>[\d]+)/edit/$', ItemUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>[\d]+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'$', ItemListView.as_view(), name='list'),
]

muypicky/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView

from menus.views import HomeView
from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view

urlpatterns = [
    url(r'^about/$', TemplateView.as_view(template_name="about.html"), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name="contact.html"), name='contact'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^profile-follow/', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^u/', include('profiles.urls', namespace='profiles')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
]

templates/snippets/css.html
<!-- Normalize CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css" />

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<style type="text/css">

.carousel, .carousel-inner {
  height: 400px;
}

.carousel > .carousel-inner > .item > img {
  position: relative;
  object-fit: cover;
  min-width: 100%;
  top: -90px;
}

.navigation > a {
	display: inline-block;
	margin: 0 5px;
}
</style>

templates/snippets/form-snippet.html
{% load crispy_forms_tags %}
{% if form.errors.non_field_errors %}
	{{ form.errors.non_field_errors }}
{% endif %}
<form method="POST"> {% csrf_token %}
	{{ form|crispy }}
	<button class="btn btn-secondary btn-block btn-lg" type="submit">Save</button>
</form>
<div style="margin-bottom: 90px;"></div>

templates/snippets/js.html
<script type="text/javascript" src="http://code.jquery.com/jquery-3.2.1.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

templates/snippets/nav.html
<div class="container text-center navigation">
	<h1>MuyPicky.com</h1>
	<a href="{% url 'home' %}">Home</a>
	{% if request.user.is_authenticated %}
	<a href="{% url 'restaurants:list' %}">Restaurants</a>
	<a href="{% url 'menus:list' %}">Menu Items</a>
	<a href="{% url 'logout' %}">Logout</a>
	{% else %}
	<a href="{% url 'login' %}">Login</a>
	<a href="{% url 'register' %}">Register</a>
	{%  endif %}
</div>

templates/snippets/sidebar.html
<ul>
	<li>Item 1</li>
	<li>Item 2</li>
	<li>Item 3</li>
</ul>